### PR TITLE
Made quality changes to header

### PR DESCRIPTION
**Pull request by Ukaypromise**
Made changes to the header styles.
Added discriptive README file.

### CODE REVIEW

**Review by gtekle — CHANGES_REQUESTED** [review]
Hi @Ukaypromise :wave:, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have enough project requirements implemented.
Kindly review the project requirements listed [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md) and try to implement them.
### Your Pull Request Page
image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by gtekle — CHANGES_REQUESTED** [review]
Hi @Ukaypromise :wave:, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have enough project requirements implemented.
Kindly review the project requirements listed [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md) and try to implement them.
### Your Pull Request Page
image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Ukaypromise** [comment]
@gtekle please what specific changes do i need to implement as i cant see anything wrong. Thanks i await your response.

**Comment by gtekle** [comment]
Hi @Ukaypromise 
I am sorry for the inconvenience, but I don't see anything to review on my side either. What I can see from my side like in the snapshot image I sent you earlier. The requirements, I am looking for are these
image

**Comment by Ukaypromise** [comment]
@gtekle please review again as i have made adjustments

**Comment by Ukaypromise** [comment]
@gtekle Please kindly review again as this is the last review i have left

**Comment by gtekle** [comment]
I am sorry I am not able to do that. The PR will be reviewed by who picked it up first. But, we can have a short call to help you on that. Kindly leave your slack handle if that is ok with you.

**Comment by Ukaypromise** [comment]
Slack handle is @PromiseUka

**Comment by Ukaypromise** [comment]
@gtekle Slack handle is @PromiseUka

**Review by HAMMAS-SALEEM — CHANGES_REQUESTED** [review]
# First of all, Welcome to Microverse :bouquet: :bouquet:

# Changes Requested :recycle:

almost there

## Hey @Ukaypromise :wave:
### Highlights :1st_place_medal:

Your project is working :clap:
Good commit history :heavy_check_mark:
Following Github Flow :heavy_check_mark:
Following HTML, CSS best practices :heavy_check_mark:
Using .gitignore file :heavy_check_mark:
Meaningful commit messages :heavy_check_mark:

You have made a great effort on your project :blush: and I can see that but you need to work on some issues to go to the next project but you are almost there. :+1:

### **_Any requested change with the optional tag is not crucial enough to prevent you from getting approval. But we, highly recommend that you to take these changes into consideration_**
## 1. 
title


- [ ] Your PR has a title that is not so descriptive enough. Because **My first pull Request!** is not describing what are you doing in the project. PR title fully describes what is happening in this branch. You could use **Feature/Setup Hello Microverse Project** or **Feature/Initialize Hello Microverse Project** for your PR title. :+1:

## 2. 
### Your Summary :nerd_face:
summary


### Descriptive Summary :heavy_check_mark:
clinton summary


###
- [ ] Your PR doesn't have a summary. Please add a summary :+1: Because a summary fully describes what is happening in this PR.

### Once you implement all the changes you should be ready to submit your project for a re-review :rocket: :rocket:

Cheers and Happy coding!👏👏👏

### Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. You can reach out to me on slack by searching my name (Hammas Bin Saleem) for any explanation.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by HAMMAS-SALEEM — APPROVED** [review]
# Status: Approved :green_circle: :tada:

Your project is complete. There is nothing else to say about that. :+1:
Go ahead and merge it :muscle:

If you want to ask any questions that comment here and tag me **@HAMMAS-SALEEM** in your comment so I will get a notification. You can also reach out to me on slack my slack handle is **@Hammas Bin Saleem**

**Pull request merged**
